import Head from "next/head";
import { Box } from "@mui/material";

import { Navbar } from "../components/navbar";
import BasicTable from "@/components/basic-table/basic-table";
import { SimpleAccordion } from "@/components/accordion";

export default function Home() {
  return (
    <>
      <Head>
        <title>PWA DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Box p={2}>
          <BasicTable />
          <br />
          <hr />
          <br />
          <SimpleAccordion />
        </Box>
      </main>
    </>
  );
}
