import Head from "next/head";
import { Button, Box, Typography } from "@mui/material";

import { Navbar } from "../components/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>PWA DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Box p={2}>
          <Typography
            component="h1"
            sx={{
              fontSize: "20px",
              fontWeight: 600,
              color: "rgb(79, 92, 129)",
            }}
          >
            Prueba pwa
          </Typography>
          <br />
          <Button
            variant="contained"
            sx={{
              backgroundColor: "#5233EA",
              "&:hover": { backgroundColor: "#5233EA" },
            }}
            onClick={() =>
              window.open(
                "https://api.whatsapp.com/send?text=Revisa%20el%20rastreo%20de%20tus%20guías%20en%20el%20siguiente%20ink%20https://next-pwa-pearl.vercel.app/"
              )
            }
          >
            Compartir en WhatsApp
          </Button>
        </Box>
      </main>
    </>
  );
}
